### Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "TestUser",
    "role": "admin",
    "password": "testpass"
}

### Get All Users
GET http://localhost:3001/api/users
Content-Type: application/json

### Get individual User
GET http://localhost:3001/api/users/648b952f409b802a0e4ec553
Content-Type: application/json

### Test - Update User
PUT http://localhost:3001/api/users/648b952f409b802a0e4ec553
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test",
    "role": "user",
    "password": "testpass"
}

### Delete User
DELETE  http://localhost:3001/api/users/648b952f409b802a0e4ec553